---
version: "2"
jobs:
  snapshot-build:
    docker:
    - image: "gradle:4.10.3"
    steps:
    - checkout:
        path: "."
    - run:
        name: "check"
        command: "gradle check -PbintrayUser=${BINTRAY_USER} -PbintrayKey=${BINTRAY_KEY}"
    - run:
        name: "report"
        command: |-
          mkdir -p ~/test-results/junit/
          find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/test-results/junit/ \;
    - store_test_results:
        path: "test-results"
  release-build:
    docker:
    - image: "gradle:4.10.3"
    steps:
    - checkout:
        path: "."
    - run:
        name: "publish"
        command: |-
          TAG=$(git --no-pager tag --sort=-taggerdate | head -n 1)
          gradle bintrayUpload -Pversion=${TAG} -PbintrayUser=${BINTRAY_USER} -PbintrayKey=${BINTRAY_KEY}
workflows:
  snapshot:
    jobs:
    - snapshot-build:
        filters:
          branches:
            only:
            - "master"
  release:
    jobs:
    - release-build:
        filters:
          branches:
            ignore:
            - "/.*/"
          tags:
            only:
            - "/\\d+\\.\\d+\\.\\d+/"
  version: 2
