---
version: "2"
jobs:
  build-snapshot:
    docker:
    - image: "gradle:4.10.3"
    steps:
    - checkout:
        path: "."
    - run:
        command: "gradle check"
  tag-release:
    docker:
    - image: "gradle:4.10.3"
    steps:
    - checkout:
        path: "."
    - run:
        command: "git --no-pager tag --sort=-taggerdate | head -n 1"
  build-release:
    docker:
    - image: "gradle:4.10.3"
    steps:
    - checkout:
        path: "."
    - run:
        command: "gradle check"
workflows:
  snapshot:
    jobs:
    - build-snapshot:
        filters:
          branches:
            only:
            - "master"
    - trigger-promotion:
        requires:
        - "build-snapshot"
        type: "approval"
    - tag-release:
        requires:
        - "trigger-promotion"
  release:
    jobs:
    - build-release:
        filters:
          branches:
            only:
            - "master"
          tags:
            only:
            - "/\\d+\\.\\d+\\.\\d+/"
  version: 2
