---
version: "2"
jobs:
  build-snapshot:
    docker:
    - image: "gradle:4.10.3"
    steps:
    - checkout:
        path: "."
    - run:
        command: |-
          gradle check
          gradle build
  tag-release:
    docker:
    - image: "gradle:4.10.3"
    steps:
    - checkout:
        path: "."
    - run:
        command: "git --no-pager tag --sort=-taggerdate | head -n 1"
workflows:
  default:
    jobs:
    - build-snapshot:
        filters:
          branches:
            only:
            - "master"
    - trigger-promotion:
        requires:
        - "build-snapshot"
        type: "approval"
    - tag-release:
        requires:
        - "trigger-promotion"
  version: 2
