---
version: "2"
jobs:
  snapshot-build:
    docker:
    - image: "gradle:4.10.3"
    steps:
    - checkout:
        path: "."
    - run:
        command: "gradle check"
  release-build:
    docker:
    - image: "gradle:4.10.3"
    steps:
    - checkout:
        path: "."
    - run:
        command: |-
          TAG=$(git --no-pager tag --sort=-taggerdate | head -n 1)
          gradle bintrayUpload -Pversion=${TAG}
workflows:
  snapshot:
    jobs:
    - snapshot-build:
        filters:
          branches:
            only:
            - "master"
  release:
    jobs:
    - release-build:
        filters:
          branches:
            ignore:
            - "/.*/"
          tags:
            only:
            - "/\\d+\\.\\d+\\.\\d+/"
  version: 2
