---
version: "2"
jobs:
  snapshot-build:
    docker:
    - image: "gradle:4.10.3"
    steps:
    - checkout:
        path: "."
    - run:
        name: "check"
        command: |-
          #!/usr/bin/env bash

          gradle check jacocoTestReport -PbintrayUser=${BINTRAY_USER} -PbintrayKey=${BINTRAY_KEY}
    - run:
        name: "report"
        command: |-
          #!/usr/bin/env bash

          mkdir -p ~/test-results/junit/
          find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/test-results/junit/ \;

          find . -type d -maxdepth 1 -name "philarios-*" -exec bash -c "mkdir -p ~/reports/{} && cp -r {}/build/reports/tests/test ~/reports/{}/junit" \;
          find . -type d -maxdepth 1 -name "philarios-*" -exec bash -c "mkdir -p ~/reports/{} && cp -r {}/build/reports/jacoco/test ~/reports/{}/jacoco" \;
    - store_test_results:
        path: "~/test-results"
    - store_artifacts:
        path: "~/reports"
  release-build:
    docker:
    - image: "gradle:4.10.3"
    steps:
    - checkout:
        path: "."
    - run:
        name: "publish"
        command: |-
          #!/usr/bin/env bash

          TAG=$(git --no-pager tag --sort=-taggerdate | head -n 1)
          gradle bintrayUpload -Pversion=${TAG} -PbintrayUser=${BINTRAY_USER} -PbintrayKey=${BINTRAY_KEY}
workflows:
  snapshot:
    jobs:
    - snapshot-build:
        filters:
          branches:
            only:
            - "master"
  release:
    jobs:
    - release-build:
        filters:
          branches:
            ignore:
            - "/.*/"
          tags:
            only:
            - "/\\d+\\.\\d+\\.\\d+/"
  version: 2
